<!DOCTYPE html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" /><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" /><title>Cosmic Ray Report</title></head><body><div class="container"><h1><p class="text-dark">Cosmic Ray Report</p></h1></div><div class="container"><div class="mb-1" id="summary_info___accordion"><div class="card"><a data-toggle="collapse" data-target="#summary_info___collapse_1" aria-expanded="true" aria-controls="summary_info___collapse_1" href="#"><div class="card-header" id="summary_info___heading_1"><button class="btn btn-outline-dark"><h4 class="m-0">Summary info</h4></button></div></a><div aria-labelledby="summary_info___heading_1" data-parent="#summary_info___accordion" class="collapse show" id="summary_info___collapse_1"><div class="card-body"><p>Date time: 20/04/2023 04:12:06</p><p>Total jobs: 19</p><p>Complete: 19 (100.00%)</p><p>Surviving mutants: 1 (5.26%)</p></div></div></div></div><div class="mb-1" id="job_list___accordion"><div class="card"><a data-toggle="collapse" data-target="#job_list___collapse_1" aria-expanded="false" aria-controls="job_list___collapse_1" href="#"><div class="card-header" id="job_list___heading_1"><button class="btn btn-outline-dark"><h4 class="m-0">Job list</h4></button></div></a><div aria-labelledby="job_list___heading_1" data-parent="#job_list___accordion" class="collapse" id="job_list___collapse_1"><div class="card-body"><div class="text-right mb-1"><div class="mx-1" id="job_item_expand_all"><a href="#" onclick="$('div.job_list___sub_multi_collapse').collapse('show');"><button class="btn btn-outline-dark"><span>Expand All</span></button></a></div><div class="mx-1" id="job_item_collapse_all"><a href="#" onclick="$('div.job_list___sub_multi_collapse').collapse('hide');"><button class="btn btn-outline-dark"><span>Collapse All</span></button></a></div></div><div class="mb-1" id="job_list___sub_accordion_1"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_1_1" aria-expanded="false" aria-controls="job_list___sub_collapse_1_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_1_1"><button class="btn btn-outline-success"><span class="job_id">1 : Job ID 216bf2c3b44246c0b441a69f3121abb6</span></button></div></a><div aria-labelledby="job_list___sub_heading_1_1" data-parent="#job_list___sub_accordion_1" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_1_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_Sub, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" - str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.55s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_2"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_2_1" aria-expanded="false" aria-controls="job_list___sub_collapse_2_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_2_1"><button class="btn btn-outline-success"><span class="job_id">2 : Job ID 65b0dd1dae4c4c949afd16849b9448fd</span></button></div></a><div aria-labelledby="job_list___sub_heading_2_1" data-parent="#job_list___sub_accordion_2" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_2_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_Mul, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" * str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: can't multiply...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: can't multiply...
======================== 48 failed, 48 passed in 0.54s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_3"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_3_1" aria-expanded="false" aria-controls="job_list___sub_collapse_3_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_3_1"><button class="btn btn-outline-success"><span class="job_id">3 : Job ID d315af2e33e84b5babf3dd1a61fe21ad</span></button></div></a><div aria-labelledby="job_list___sub_heading_3_1" data-parent="#job_list___sub_accordion_3" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_3_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_Div, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" / str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.54s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_4"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_4_1" aria-expanded="false" aria-controls="job_list___sub_collapse_4_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_4_1"><button class="btn btn-outline-success"><span class="job_id">4 : Job ID 4e6145f5f0a34fe8a961e9de19bb307a</span></button></div></a><div aria-labelledby="job_list___sub_heading_4_1" data-parent="#job_list___sub_accordion_4" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_4_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_FloorDiv, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" // str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.55s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_5"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_5_1" aria-expanded="false" aria-controls="job_list___sub_collapse_5_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_5_1"><button class="btn btn-outline-success"><span class="job_id">5 : Job ID d82030e23f984bca90ea906d5034f0f1</span></button></div></a><div aria-labelledby="job_list___sub_heading_5_1" data-parent="#job_list___sub_accordion_5" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_5_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_Mod, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" % str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: not all argume...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: not all argume...
======================== 48 failed, 48 passed in 0.55s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_6"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_6_1" aria-expanded="false" aria-controls="job_list___sub_collapse_6_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_6_1"><button class="btn btn-outline-success"><span class="job_id">6 : Job ID b1538b3f6c974149942fa4a1722d4c82</span></button></div></a><div aria-labelledby="job_list___sub_heading_6_1" data-parent="#job_list___sub_accordion_6" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_6_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_Pow, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" ** str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.54s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_7"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_7_1" aria-expanded="false" aria-controls="job_list___sub_collapse_7_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_7_1"><button class="btn btn-outline-success"><span class="job_id">7 : Job ID 366c6c7b8efc4d28855eba0d5c78d6d5</span></button></div></a><div aria-labelledby="job_list___sub_heading_7_1" data-parent="#job_list___sub_accordion_7" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_7_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_RShift, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" &gt;&gt; str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.54s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_8"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_8_1" aria-expanded="false" aria-controls="job_list___sub_collapse_8_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_8_1"><button class="btn btn-outline-success"><span class="job_id">8 : Job ID 99d644328cd74820ac08fdbd7017c446</span></button></div></a><div aria-labelledby="job_list___sub_heading_8_1" data-parent="#job_list___sub_accordion_8" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_8_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_LShift, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" &lt;&lt; str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.54s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_9"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_9_1" aria-expanded="false" aria-controls="job_list___sub_collapse_9_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_9_1"><button class="btn btn-outline-success"><span class="job_id">9 : Job ID f006fa61f6bd40aa8a183b5c716217e1</span></button></div></a><div aria-labelledby="job_list___sub_heading_9_1" data-parent="#job_list___sub_accordion_9" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_9_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_BitOr, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" | str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.55s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_10"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_10_1" aria-expanded="false" aria-controls="job_list___sub_collapse_10_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_10_1"><button class="btn btn-outline-success"><span class="job_id">10 : Job ID 8e150a337944445f9c91c24213049d8f</span></button></div></a><div aria-labelledby="job_list___sub_heading_10_1" data-parent="#job_list___sub_accordion_10" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_10_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_BitAnd, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" &amp; str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.54s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_11"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_11_1" aria-expanded="false" aria-controls="job_list___sub_collapse_11_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_11_1"><button class="btn btn-outline-success"><span class="job_id">11 : Job ID 0db68e1264c14f3fa3f216ae30d76aa7</span></button></div></a><div aria-labelledby="job_list___sub_heading_11_1" data-parent="#job_list___sub_accordion_11" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_11_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=27" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (27, 24), end pos: (27, 25)</button></a></pre><pre>operator: core/ReplaceBinaryOperator_Add_BitXor, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -24,5 +24,5 @@
 
     def __repr__(self):
         """show representation."""
-        return "stack:" + str(self.stack)
+        return "stack:" ^ str(self.stack)
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ............FF.FFF.F..F..FFFFFFFF.F..FF.F.F [ 44%]
.FF..FF.FF...FFF...F.....FFFFFF..FFFFF.......FFFFFFF.                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - TypeError: unsupported op...
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - TypeError: unsupported op...
======================== 48 failed, 48 passed in 0.55s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_12"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_12_1" aria-expanded="false" aria-controls="job_list___sub_collapse_12_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_12_1"><button class="btn btn-outline-success"><span class="job_id">12 : Job ID b33fe4fdaee5403b98f223ace7bd2755</span></button></div></a><div aria-labelledby="job_list___sub_heading_12_1" data-parent="#job_list___sub_accordion_12" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_12_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 31), end pos: (13, 33)</button></a></pre><pre>operator: core/ReplaceComparisonOperator_Eq_NotEq, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) != 0
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py .FFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF [ 44%]
FFFFFFFFFF..FFFFFFFF.FFFFFFFFFFFFFFFFF.F.FFFFFFFFFFFF                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_1 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_2 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_3 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_4 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_5 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_7 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_8 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_9 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_10 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_11 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_14 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_18 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_20 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_21 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_23 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_24 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_33 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_35 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_36 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_41 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_43 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_46 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_47 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_50 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_55 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_59 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_60 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_61 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_64 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_65 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_66 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_67 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_74 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_75 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_82 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_84 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_85 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_86 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_87 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_95 - assert False is True
========================= 88 failed, 8 passed in 0.57s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_13"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_13_1" aria-expanded="false" aria-controls="job_list___sub_collapse_13_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_13_1"><button class="btn btn-outline-success"><span class="job_id">13 : Job ID 259bc06eb7ca4e4fa089c67dfa7758d8</span></button></div></a><div aria-labelledby="job_list___sub_heading_13_1" data-parent="#job_list___sub_accordion_13" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_13_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 31), end pos: (13, 33)</button></a></pre><pre>operator: core/ReplaceComparisonOperator_Eq_Lt, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) &lt; 0
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py .FFFFF.FF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF [ 44%]
FFFFFFFFFF..FFFFFFFF.FFFFFFFFFFFFFFFFF.F.FFFFFFFFFFFF                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_1 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_2 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_3 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_4 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_5 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_7 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_8 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_10 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_11 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_14 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_18 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_20 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_21 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_23 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_24 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_33 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_35 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_36 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_41 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_43 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_46 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_47 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_50 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_55 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_59 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_60 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_61 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_64 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_65 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_66 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_67 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_74 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_75 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_82 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_84 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_85 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_86 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_87 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_95 - assert False is True
========================= 87 failed, 9 passed in 0.57s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_14"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_14_1" aria-expanded="false" aria-controls="job_list___sub_collapse_14_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-danger" id="job_list___sub_heading_14_1"><button class="btn btn-outline-danger"><span class="job_id">14 : Job ID 0f5e8553aea8472c89067bcf7b82453d</span></button></div></a><div aria-labelledby="job_list___sub_heading_14_1" data-parent="#job_list___sub_accordion_14" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_14_1"><div class="card-body"><div class="work-item"><div class="alert alert-danger test-outcome" role="alert"><p>SURVIVED</p><p>worker outcome: normal</p><p>test outcome: survived</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 31), end pos: (13, 33)</button></a></pre><pre>operator: core/ReplaceComparisonOperator_Eq_LtE, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) &lt;= 0
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ........................................... [ 44%]
.....................................................                    [100%]

============================== 96 passed in 0.52s ==============================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_15"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_15_1" aria-expanded="false" aria-controls="job_list___sub_collapse_15_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_15_1"><button class="btn btn-outline-success"><span class="job_id">15 : Job ID 389e8272d3474ccda41ff2e0b52c8777</span></button></div></a><div aria-labelledby="job_list___sub_heading_15_1" data-parent="#job_list___sub_accordion_15" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_15_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 31), end pos: (13, 33)</button></a></pre><pre>operator: core/ReplaceComparisonOperator_Eq_Gt, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) &gt; 0
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py .FFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF [ 44%]
FFFFFFFFFF..FFFFFFFF.FFFFFFFFFFFFFFFFF.F.FFFFFFFFFFFF                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_1 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_2 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_3 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_4 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_5 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_7 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_8 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_9 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_10 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_11 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_14 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_18 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_20 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_21 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_23 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_24 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_33 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_35 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_36 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_41 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_43 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_46 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_47 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_50 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_55 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_59 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_60 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_61 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_64 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_65 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_66 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_67 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_74 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_75 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_82 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_84 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_85 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_86 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_87 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_95 - assert False is True
========================= 88 failed, 8 passed in 0.57s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_16"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_16_1" aria-expanded="false" aria-controls="job_list___sub_collapse_16_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_16_1"><button class="btn btn-outline-success"><span class="job_id">16 : Job ID 6c7d6d865ea942e084edfbcfdc7f3bb0</span></button></div></a><div aria-labelledby="job_list___sub_heading_16_1" data-parent="#job_list___sub_accordion_16" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_16_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 31), end pos: (13, 33)</button></a></pre><pre>operator: core/ReplaceComparisonOperator_Eq_GtE, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) &gt;= 0
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py .........FF..FF.FF.FFFF..F..FFFF...FF.F.F.. [ 44%]
.FF..FF.F...FF..F..F...F.F.FFF....FFFF...F...FFF.FF..                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_9 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_10 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_14 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_20 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_21 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_35 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_36 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_55 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_59 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_66 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_84 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - assert True is False
======================== 43 failed, 53 passed in 0.57s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_17"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_17_1" aria-expanded="false" aria-controls="job_list___sub_collapse_17_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_17_1"><button class="btn btn-outline-success"><span class="job_id">17 : Job ID 75429d4be203408c9458f71e776d93c6</span></button></div></a><div aria-labelledby="job_list___sub_heading_17_1" data-parent="#job_list___sub_accordion_17" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_17_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=21" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (21, 11), end pos: (21, 25)</button></a></pre><pre>operator: core/AddNot, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -18,7 +18,7 @@
 
     def pop(self):
         """Remove topmost element and return it. O(1) performance."""
-        if self.isEmpty():
+        if not self.isEmpty():
             raise Exception('Stack is empty.')
         return self.stack.pop()
 </pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py ........................................... [ 44%]
...................F.................................                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - Exception: Stack is empty.
========================= 1 failed, 95 passed in 0.52s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_18"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_18_1" aria-expanded="false" aria-controls="job_list___sub_collapse_18_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_18_1"><button class="btn btn-outline-success"><span class="job_id">18 : Job ID b26fb8dfc5bd429188b8f49c492d2add</span></button></div></a><div aria-labelledby="job_list___sub_heading_18_1" data-parent="#job_list___sub_accordion_18" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_18_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 34), end pos: (13, 35)</button></a></pre><pre>operator: core/NumberReplacer, occurrence: 0</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) == 1
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py .FFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF [ 44%]
FFFFFFFFFF..FFFFFFFF.FFFFFFFFFFFFFFFFF.F.FFFFFFFFFFFF                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_1 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_2 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_3 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_4 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_5 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_7 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_8 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_9 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_10 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_11 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_14 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_18 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_20 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_21 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_23 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_24 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_33 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_35 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_36 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_41 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_43 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_46 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_47 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_50 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_55 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_59 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_60 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_61 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_64 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_65 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_66 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_67 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_74 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_75 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_82 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_84 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_85 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_86 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_87 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - assert True is False
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_95 - assert False is True
========================= 88 failed, 8 passed in 0.58s =========================
</pre></div></div></div></div></div><div class="mb-1" id="job_list___sub_accordion_19"><div class="card"><a data-toggle="collapse" data-target="#job_list___sub_collapse_19_1" aria-expanded="false" aria-controls="job_list___sub_collapse_19_1" href="#" class="job_list___sub_multi_heading"><div role="alert" class="card-header alert-success" id="job_list___sub_heading_19_1"><button class="btn btn-outline-success"><span class="job_id">19 : Job ID 901a82e5753f45c88e10db0a9296eecb</span></button></div></a><div aria-labelledby="job_list___sub_heading_19_1" data-parent="#job_list___sub_accordion_19" class="collapse job_list___sub_multi_collapse" id="job_list___sub_collapse_19_1"><div class="card-body"><div class="work-item"><div class="alert alert-success test-outcome" role="alert"><p>worker outcome: normal</p><p>test outcome: killed</p></div></div><pre class="location"><a href="pycharm://open?file=stack2.py&amp;line=13" class="text-secondary"><button class="btn btn-outline-dark">stack2.py, start pos: (13, 34), end pos: (13, 35)</button></a></pre><pre>operator: core/NumberReplacer, occurrence: 1</pre><div class="alert alert-secondary"><pre class="diff">--- mutation diff ---
--- astack2.py
+++ bstack2.py
@@ -10,7 +10,7 @@
 
     def isEmpty(self):
         """Determines whether stack is empty. O(1) performance"""
-        return len(self.stack) == 0
+        return len(self.stack) == -1
 
     def push(self, v):
         """Push v onto the stack. O(1) performance."""</pre></div><div class="alert alert-secondary"><pre class="diff">============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack2
collected 96 items

RANDOM/test_stack2_RANDOM.py .FFFFF.FF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF [ 44%]
FFFFFFFFFF..FFFFFFFF.FFFFFFFFFFFFFFFFF.F.FFFFFFFFFFFF                    [100%]

=========================== short test summary info ============================
FAILED RANDOM/test_stack2_RANDOM.py::test_case_1 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_2 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_3 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_4 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_5 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_7 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_8 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_10 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_11 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_12 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_13 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_14 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_15 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_16 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_17 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_18 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_19 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_20 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_21 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_22 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_23 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_24 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_25 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_26 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_27 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_28 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_29 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_30 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_31 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_32 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_33 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_34 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_35 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_36 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_37 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_38 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_40 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_41 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_42 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_43 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_44 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_45 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_46 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_47 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_48 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_49 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_50 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_51 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_52 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_55 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_56 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_57 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_58 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_59 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_60 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_61 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_62 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_64 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_65 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_66 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_67 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_68 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_69 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_70 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_71 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_72 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_73 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_74 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_75 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_76 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_77 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_78 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_79 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_80 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_82 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_84 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_85 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_86 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_87 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_88 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_89 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_90 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_91 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_92 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_93 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_94 - assert False is True
FAILED RANDOM/test_stack2_RANDOM.py::test_case_95 - assert False is True
========================= 87 failed, 9 passed in 0.57s =========================
</pre></div></div></div></div></div></div></div></div></div></div><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script><script type="text/javascript">$('div.job_list___sub_multi_collapse').on('shown.bs.collapse',  function () {    correct_behavior_functional_buttons();  });$('div.job_list___sub_multi_collapse').on('hidden.bs.collapse',  function () {    correct_behavior_functional_buttons();  });function correct_behavior_functional_buttons() {    var expand = false;    var collapse = false;    $('a.job_list___sub_multi_heading').each(function(index) {      if ($(this).attr('aria-expanded') == 'false') {        expand = true;        return false;      };    });    $('a.job_list___sub_multi_heading').each(function(index) {      if ($(this).attr('aria-expanded') == 'true') {        collapse = true;        return false;      };    });    if (expand) {      $('div#job_item_expand_all').css('display', 'inline-block');    } else {      $('div#job_item_expand_all').css('display', 'none');    };    if (collapse) {      $('div#job_item_collapse_all').css('display', 'inline-block');    } else {      $('div#job_item_collapse_all').css('display', 'none');    };  };correct_behavior_functional_buttons();</script></body></html>
